import type { Section } from "../state";

export const dataplaneSearchSectionByKind: Record<string, Section> = {
  namespaces: "namespaces",
  nodes: "nodes",
  pods: "pods",
  deployments: "deployments",
  daemonsets: "daemonsets",
  statefulsets: "statefulsets",
  replicasets: "replicasets",
  jobs: "jobs",
  cronjobs: "cronjobs",
  horizontalpodautoscalers: "horizontalpodautoscalers",
  services: "services",
  ingresses: "ingresses",
  networkpolicies: "networkpolicies",
  configmaps: "configmaps",
  secrets: "secrets",
  serviceaccounts: "serviceaccounts",
  roles: "roles",
  rolebindings: "rolebindings",
  persistentvolumeclaims: "persistentvolumeclaims",
  helmreleases: "helm",
  resourcequotas: "resourcequotas",
  limitranges: "limitranges",
};
